export const CARDS = [
  {
    id: 1,
    title: "Vazados das Famosinhas (PT)",
    description: "Os flagras mais comentados das criadoras portuguesas — direto das stories e DMs privados.",
    badge: "🔥 EM ALTA",
    cta: "Liberar Acesso",
    image: "/fotos/card1.gif",
    stats: { videos: 47, fotos: 312, views: "89K", membros: "2,3K" },
    price: "€19,90",
    priceAmount: 19.90,
    originalPrice: "€39,90",
    rating: 4.9,
    reviews: 318,
  },
  {
    id: 2,
    title: "OnlyFans & Privacy VIP",
    description: "Pastas ocultas e conteúdos exclusivos de perfis privados portugueses.",
    badge: "💎 PRIVADO",
    cta: "Abrir Pasta",
    image: "/fotos/card2.gif",
    stats: { videos: 23, fotos: 156, views: "54K", membros: "1,8K" },
    price: "€24,90",
    priceAmount: 24.90,
    originalPrice: "€49,90",
    rating: 4.8,
    reviews: 204,
  },
  {
    id: 3,
    title: "Amadoras & Flagras Reais",
    description: "Conteúdo real, sem edições, de amadoras portuguesas — exatamente como foi captado.",
    badge: "📸 NOVIDADE",
    cta: "Ver Fotos/Vídeos",
    image: "/fotos/card3.gif",
    stats: { videos: 61, fotos: 428, views: "112K", membros: "3,1K" },
    price: "€14,90",
    priceAmount: 14.90,
    originalPrice: "€29,90",
    rating: 4.9,
    reviews: 521,
  },
  {
    id: 4,
    title: "Transexuais Portuguesas Vazadas",
    description: "Cenas privadas e exclusivas das criadoras trans mais seguidas em Portugal — sem censura.",
    badge: "🌟 EXCLUSIVO",
    cta: "Aceder ao Conteúdo",
    image: "/fotos/card4.mp4",
    stats: { videos: 34, fotos: 201, views: "67K", membros: "1,4K" },
    price: "€19,90",
    priceAmount: 19.90,
    originalPrice: "€39,90",
    rating: 4.8,
    reviews: 176,
  },
  {
    id: 5,
    title: "Canais de Telegram Secretos",
    description: "Links diretos e sem censura para os grupos mais exclusivos — sem listas de espera.",
    badge: "⚡ IMEDIATO",
    cta: "Entrar no Grupo",
    image: "/fotos/card5.gif",
    stats: { videos: 0, fotos: 0, views: "38K", membros: "12K" },
    price: "€9,90",
    priceAmount: 9.90,
    originalPrice: "€19,90",
    rating: 4.7,
    reviews: 893,
  },
  {
    id: 6,
    title: "Arquivos Excluídos & Backstage",
    description: "Conteúdos apagados das redes sociais que o algoritmo removeu — recuperados aqui.",
    badge: "🚫 EXPIRANDO",
    cta: "Recuperar Conteúdos",
    image: "/fotos/card6.gif",
    stats: { videos: 29, fotos: 187, views: "43K", membros: "890" },
    price: "€17,90",
    priceAmount: 17.90,
    originalPrice: "€34,90",
    rating: 4.8,
    reviews: 142,
  },
  {
    id: 7,
    title: "Pack Premium da Semana",
    description: "Coletânea selecionada da semana com o melhor conteúdo das criadoras portuguesas.",
    badge: "⭐ COMPLETO",
    cta: "Baixar Pack",
    image: "/fotos/card7.gif",
    stats: { videos: 38, fotos: 264, views: "78K", membros: "2,7K" },
    price: "€29,90",
    priceAmount: 29.90,
    originalPrice: "€59,90",
    rating: 4.9,
    reviews: 437,
  },
] as const;

export type Card = typeof CARDS[number];
